### ISSUE TITLE
Add instructions on how to build

### ISSUE THREAD

**Issue by Earu** [emily33901/Argon#1]
I'm not sure whether this repository is maintained or not but it would be great to have steps to follow on how to build / use this replacement. Thanks in advance.

**Comment by emily33901** [comment]
Never finished it properly so it wouldnt work in its current state. You can run ./premake5 gmake or premake5 vs2017 to build the c++ part and then use the dotnet core tools to build the .sln file in the base of src/

i would recommend looking at https://github.com/emily33901/argonx which is a rewrite of alot of this in c++

**Comment by Earu** [comment]
I see thanks for your time.
